name: Run Tests on Push

on:
  push:
    branches:
      - main # or master, develop, etc. - the branch you want to trigger tests on
  workflow_call: {}

jobs:
  test:
    runs-on: ubuntu-latest # or windows-latest, macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # Use a recent version of the checkout action

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' # Specify your desired Python version, e.g., '3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest==7.4.4 pytest-spec requests

      - name: Debug â€” list files
        run: ls -R
        
      - name: Run tests
        run: pytest --spec 
